# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-alpine

# Install dependencies
RUN apk add --no-cache gcc musl-dev linux-headers

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Install project dependencies
RUN pip install --no-cache-dir .

# Expose any necessary ports (if applicable, though MCP uses stdio)

# Run the server
CMD ["python", "-m", "iotdb_mcp_server.server"]
